{{- if .Values.global.gluster.enable }}
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: elastic-transcoder
subsets:
- addresses:
  - ip: {{ .Values.global.gluster.address }} 
  ports:
  - port: 1
{{-end }}  