path:
    media:
        flat: /media/elastictranscoder-data/FlatMedia/
        transcode: /media/elastictranscoder-data/TranscodeMedia/
logging:
  level:
    es:
      videotranscoding: INFO             
cloud:
  aws:
    region:
      static: eu-west-1
    stack:
      auto: false  
    sqs:
      endpoint:
        uri: 
          media-info: https://sqs.eu-west-1.amazonaws.com/836783797541/media-info 
