package es.videotranscoding.media.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@Builder
@NoArgsConstructor
@DynamoDBTable(tableName = "transcode_media")
public class TranscodeMedia {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "flatMediaId-index")
    private String flatMediaId;

    private String type;

    private String name;

    private String path;

    private String audioCodec;

    private String videoCodec;

    private String container;

    private String preset;

    private String resolution;

    private double processed;

    private String command;

    private Boolean active;

    private Boolean error;
    
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "user-index")
    private String user;

    private String filesize;

    private String bitrate;
}
