package es.videotranscoding.transcoder.status.model;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Data
@Builder
@NoArgsConstructor
@DynamoDBTable(tableName = "flat_media")
public class FlatMedia {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    private String type;

    private String name;

    private String path;
    
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "user-index")
    private String user;

    private String filesize;

    private Boolean active;

    private String bitrate;

    private String container;

    private String audioCodec;

    private String resolution;

    private String videoCodec;

    private String duration;

}